<?php

namespace App\DataFixtures;

use App\Entity\Category;
use App\Entity\Product;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class ProductFixtures extends Fixture implements DependentFixtureInterface
{
    // Constantes pour pouvoir référencer les produits depuis ImageFixtures
    public const PRODUCT_REFERENCE_PREFIX = 'product-';

    public function load(ObjectManager $manager): void
    {
        $products = [
            // === Textile ===
            ['title' => 'Coussin bohème',     'price' => 25.99,  'category' => CategoryFixtures::CATEGORY_TEXTILE, 'description' => 'Ce coussin décoratif au style bohème apporte une touche chaleureuse et authentique à votre intérieur. Conçu avec des matériaux de qualité, il se distingue par ses motifs inspirés de l\'artisanat traditionnel et ses couleurs naturelles qui s\'intègrent facilement dans différents styles de décoration. Idéal pour un canapé, un fauteuil ou un lit, il offre également un confort agréable pour vos moments de détente. Sa texture douce et son rembourrage généreux en font un accessoire aussi esthétique que pratique. Parfait pour créer une ambiance cosy et accueillante, ce coussin deviendra rapidement un élément incontournable de votre décoration.'],
            ['title' => 'Plaid doux',         'price' => 39.90,  'category' => CategoryFixtures::CATEGORY_TEXTILE, 'description' => 'Ce plaid doux et confortable est l\'accessoire parfait pour réchauffer vos soirées tout en ajoutant une touche élégante à votre décoration intérieure. Fabriqué dans un tissu moelleux et agréable au toucher, il vous enveloppe de chaleur dès les premiers instants. Idéal pour un canapé ou un lit, il s\'adapte à toutes les saisons et styles d\'intérieur. Sa finition soignée et sa texture légère permettent un usage quotidien sans compromettre son aspect esthétique. Que ce soit pour se détendre devant un film ou pour décorer votre salon, ce plaid est un choix à la fois pratique et raffiné.'],
            ['title' => 'Rideaux en lin',     'price' => 59.00,  'category' => CategoryFixtures::CATEGORY_TEXTILE, 'description' => 'Ces rideaux en lin naturel apportent une élégance discrète et une atmosphère apaisante à votre intérieur. Le tissu léger filtre délicatement la lumière, créant une ambiance douce et lumineuse dans votre pièce. Leur texture authentique et leur finition soignée s\'intègrent parfaitement dans une décoration moderne, rustique ou minimaliste. Faciles à installer, ils offrent également une bonne intimité tout en laissant passer la clarté extérieure. Leur durabilité et leur qualité en font un investissement idéal pour habiller vos fenêtres avec style. Ces rideaux sont parfaits pour sublimer votre salon, chambre ou bureau.'],
            ['title' => 'Tapis berbère',      'price' => 120.00, 'category' => CategoryFixtures::CATEGORY_TEXTILE, 'description' => 'Ce tapis berbère artisanal est une pièce unique qui apporte du caractère et de la chaleur à votre intérieur. Inspiré des traditions ancestrales, il présente des motifs géométriques authentiques et des textures riches qui attirent le regard. Fabriqué avec soin à partir de matériaux de qualité, il offre un confort agréable sous les pieds tout en étant résistant à l\'usage quotidien. Idéal pour un salon ou une chambre, il structure l\'espace et ajoute une dimension chaleureuse à votre décoration. Son style intemporel s\'adapte aussi bien aux intérieurs modernes qu\'aux ambiances plus traditionnelles.'],

            // === Lumière ===
            ['title' => 'Lampe de chevet',    'price' => 45.50,  'category' => CategoryFixtures::CATEGORY_LUMIERE, 'description' => 'Cette lampe de chevet moderne combine design élégant et fonctionnalité pour illuminer votre espace avec style. Parfaite pour une chambre, elle offre une lumière douce et agréable, idéale pour la lecture ou pour créer une ambiance relaxante en fin de journée. Sa conception compacte permet de l\'installer facilement sur une table de nuit sans encombrer l\'espace. Les matériaux utilisés assurent une bonne durabilité tout en conservant une esthétique contemporaine. Elle s\'intègre harmonieusement dans différents styles de décoration, du minimaliste au plus sophistiqué. Cette lampe est un choix pratique et esthétique pour améliorer votre confort quotidien.'],
            ['title' => 'Suspension design',  'price' => 89.99,  'category' => CategoryFixtures::CATEGORY_LUMIERE, 'description' => 'Cette suspension design en métal est un véritable élément central pour sublimer votre intérieur. Son style moderne et épuré attire immédiatement l\'attention et apporte une touche contemporaine à votre pièce. Idéale pour un salon, une salle à manger ou une cuisine, elle diffuse une lumière homogène et agréable. Sa structure solide et ses finitions soignées garantissent une excellente durabilité. Facile à installer, elle s\'adapte à différentes hauteurs de plafond et configurations d\'espace. Cette suspension est parfaite pour créer une ambiance élégante et lumineuse tout en affirmant votre style décoratif.'],
            ['title' => 'Guirlande LED',      'price' => 19.99,  'category' => CategoryFixtures::CATEGORY_LUMIERE, 'description' => 'Cette guirlande LED est idéale pour créer une ambiance chaleureuse et cosy dans votre intérieur ou votre extérieur. Grâce à ses lumières douces et économiques, elle apporte une touche féerique à vos soirées et événements. Facile à installer, elle peut être disposée sur un meuble, autour d\'un lit ou sur une terrasse. Sa faible consommation d\'énergie en fait une solution durable et pratique pour illuminer votre espace. Résistante et polyvalente, elle s\'adapte à toutes les occasions, qu\'il s\'agisse d\'une décoration quotidienne ou festive. Elle est parfaite pour ajouter une atmosphère lumineuse et accueillante.'],
            ['title' => 'Lampe sur pied',     'price' => 75.00,  'category' => CategoryFixtures::CATEGORY_LUMIERE, 'description' => 'Cette lampe sur pied élégante est idéale pour illuminer votre salon tout en apportant une touche raffinée à votre décoration. Son design moderne s\'intègre parfaitement dans différents styles d\'intérieur, du contemporain au classique. Elle diffuse une lumière agréable qui peut servir à la fois d\'éclairage principal ou d\'appoint. Sa structure stable et ses matériaux de qualité assurent une longue durée de vie. Facile à déplacer, elle peut être placée près d\'un canapé ou dans un coin lecture. Cette lampe est parfaite pour créer une ambiance chaleureuse et confortable dans votre espace de vie.'],

            // === Mural ===
            ['title' => 'Tableau abstrait',   'price' => 60.00,  'category' => CategoryFixtures::CATEGORY_MURAL, 'description' => 'Ce tableau abstrait est une œuvre moderne qui apporte une touche artistique unique à votre intérieur. Ses formes et couleurs créent une composition visuelle captivante qui attire immédiatement le regard. Idéal pour un salon, une chambre ou un bureau, il permet de personnaliser votre espace avec élégance. Réalisé avec des matériaux de qualité, il offre une excellente durabilité et une finition soignée. Il s\'intègre facilement dans différents styles de décoration, qu\'ils soient contemporains ou plus classiques. Ce tableau est parfait pour exprimer votre sens artistique et enrichir votre environnement quotidien.'],
            ['title' => 'Miroir rond',        'price' => 55.00,  'category' => CategoryFixtures::CATEGORY_MURAL, 'description' => 'Ce miroir rond décoratif est un élément incontournable pour agrandir visuellement votre espace tout en apportant une touche élégante. Sa forme douce et harmonieuse s\'adapte facilement à tous les styles de décoration. Placé dans une entrée, un salon ou une chambre, il reflète la lumière et crée une impression de profondeur. Sa finition soignée et ses matériaux de qualité assurent une excellente durabilité. Facile à installer, il devient rapidement un point focal dans votre pièce. Ce miroir combine fonctionnalité et esthétique pour sublimer votre intérieur avec simplicité.'],
            ['title' => 'Affiche vintage',    'price' => 15.00,  'category' => CategoryFixtures::CATEGORY_MURAL, 'description' => 'Cette affiche vintage au style rétro est parfaite pour apporter du caractère et une touche nostalgique à votre décoration. Inspirée des designs anciens, elle évoque une époque pleine de charme et d\'élégance. Idéale pour un salon, une chambre ou un bureau, elle s\'intègre facilement dans différents styles d\'intérieur. Son impression de qualité garantit des couleurs durables et un rendu visuel attrayant. Facile à encadrer ou à afficher telle quelle, elle permet de personnaliser votre espace selon vos goûts. Cette affiche est un choix idéal pour les amateurs de décoration authentique et originale.'],
            ['title' => 'Horloge murale',     'price' => 35.00,  'category' => CategoryFixtures::CATEGORY_MURAL, 'description' => 'Cette horloge murale au design minimaliste allie esthétique et fonctionnalité pour s\'intégrer parfaitement dans votre intérieur. Son style épuré permet une lecture facile de l\'heure tout en apportant une touche moderne à votre décoration. Idéale pour un salon, une cuisine ou un bureau, elle s\'adapte à différents espaces sans les surcharger visuellement. Sa conception robuste garantit une longue durée de vie et un fonctionnement précis. Facile à installer, elle devient rapidement un élément essentiel du quotidien. Cette horloge est parfaite pour ceux qui recherchent un objet à la fois pratique et élégant.'],

            // === Décor ===
            ['title' => 'Vase en céramique',  'price' => 29.99,  'category' => CategoryFixtures::CATEGORY_DECOR, 'description' => 'Ce vase en céramique fait main est un objet décoratif unique qui apporte une touche artisanale à votre intérieur. Sa texture et ses finitions témoignent d\'un savoir-faire authentique, rendant chaque pièce légèrement différente. Idéal pour accueillir des fleurs fraîches ou séchées, il peut également être utilisé comme élément décoratif seul. Sa forme élégante et ses couleurs naturelles s\'intègrent facilement dans différents styles de décoration. Robuste et durable, il conserve son aspect esthétique au fil du temps. Ce vase est parfait pour enrichir votre espace avec une note artistique et chaleureuse.'],
            ['title' => 'Bougie parfumée',    'price' => 12.50,  'category' => CategoryFixtures::CATEGORY_DECOR, 'description' => 'Cette bougie parfumée à la senteur vanille crée une ambiance douce et relaxante dans votre intérieur. Son parfum délicat se diffuse progressivement pour offrir une expérience sensorielle agréable et apaisante. Idéale pour les moments de détente, elle peut être utilisée dans un salon, une chambre ou une salle de bain. Sa fabrication soignée assure une combustion homogène et durable. Son design élégant en fait également un bel objet décoratif. Cette bougie est parfaite pour instaurer une atmosphère chaleureuse et réconfortante au quotidien.'],
            ['title' => 'Statue déco',        'price' => 40.00,  'category' => CategoryFixtures::CATEGORY_DECOR, 'description' => 'Cette statue décorative moderne est un élément artistique qui apporte une touche d\'originalité à votre intérieur. Son design contemporain attire le regard et s\'intègre parfaitement dans un espace de vie ou un bureau. Fabriquée avec des matériaux de qualité, elle offre une bonne durabilité tout en conservant une esthétique raffinée. Elle peut être placée sur une étagère, une table ou un meuble pour compléter votre décoration. Cette statue est idéale pour exprimer votre style personnel et enrichir votre environnement avec une pièce unique.'],
            ['title' => 'Plante artificielle','price' => 22.00,  'category' => CategoryFixtures::CATEGORY_DECOR, 'description' => 'Cette plante artificielle est une solution idéale pour apporter une touche de verdure à votre intérieur sans les contraintes d\'entretien. Son apparence réaliste imite parfaitement les plantes naturelles, créant une ambiance fraîche et agréable. Elle convient parfaitement aux personnes ayant peu de temps ou sans accès à la lumière naturelle. Facile à placer dans n\'importe quelle pièce, elle s\'intègre dans différents styles de décoration. Durable et résistante, elle conserve son aspect esthétique au fil du temps. Cette plante est parfaite pour embellir votre espace de manière simple et efficace.'],

            // === Pratique ===
            ['title' => 'Panier de rangement','price' => 18.00,  'category' => CategoryFixtures::CATEGORY_PRATIQUE, 'description' => 'Ce panier de rangement en osier est une solution pratique et esthétique pour organiser votre intérieur. Sa conception robuste permet de stocker divers objets tels que des couvertures, des jouets ou des accessoires du quotidien. Son style naturel s\'intègre facilement dans différents types de décoration, du rustique au moderne. Léger et facile à déplacer, il peut être utilisé dans plusieurs pièces de la maison. Sa fabrication de qualité garantit une bonne durabilité. Ce panier est idéal pour garder un espace propre et ordonné tout en ajoutant une touche décorative.'],
            ['title' => 'Boîte de stockage',  'price' => 14.50,  'category' => CategoryFixtures::CATEGORY_PRATIQUE, 'description' => 'Cette boîte de stockage avec couvercle est parfaite pour organiser efficacement vos affaires tout en protégeant leur contenu. Son design pratique permet un empilage facile, optimisant ainsi l\'espace disponible. Idéale pour une utilisation dans un placard, un bureau ou un garage, elle s\'adapte à différents besoins de rangement. Fabriquée avec des matériaux solides, elle assure une bonne résistance à l\'usage quotidien. Son couvercle protège contre la poussière et l\'humidité. Cette boîte est une solution simple et efficace pour maintenir un environnement ordonné.'],
            ['title' => 'Porte-manteau',      'price' => 32.00,  'category' => CategoryFixtures::CATEGORY_PRATIQUE, 'description' => 'Ce porte-manteau mural est une solution pratique pour organiser vos vêtements et accessoires au quotidien. Son design fonctionnel permet d\'accrocher manteaux, sacs ou chapeaux de manière simple et accessible. Idéal pour une entrée ou une chambre, il optimise l\'espace tout en ajoutant une touche décorative. Sa structure robuste garantit une bonne résistance au poids et à l\'usage fréquent. Facile à installer, il s\'adapte à différents styles d\'intérieur. Ce porte-manteau est parfait pour garder votre espace bien organisé et accueillant.'],
            ['title' => 'Étagère murale',     'price' => 48.00,  'category' => CategoryFixtures::CATEGORY_PRATIQUE, 'description' => 'Cette étagère murale simple et moderne est idéale pour optimiser votre espace tout en mettant en valeur vos objets décoratifs. Elle permet de ranger livres, plantes ou accessoires de manière esthétique et fonctionnelle. Son design épuré s\'intègre facilement dans différents styles d\'intérieur. Fabriquée avec des matériaux de qualité, elle offre une bonne stabilité et durabilité. Facile à installer, elle convient à toutes les pièces de la maison. Cette étagère est parfaite pour combiner rangement et décoration avec élégance.'],
        ];

        foreach ($products as $index => $data) {
            $product = new Product();
            $product->setTitle($data['title']);
            $product->setDescription($data['description']);
            $product->setPrice($data['price']);

            // Récupération de la catégorie via la référence stockée dans CategoryFixtures
            $category = $this->getReference($data['category'], Category::class);
            $product->setCategory($category);

            $manager->persist($product);

            // Référence du produit (pour ImageFixtures qui en aura besoin)
            // Index commence à 0 → on ajoute +1 pour matcher l'id (1, 2, 3...)
            $this->addReference(self::PRODUCT_REFERENCE_PREFIX . ($index + 1), $product);
        }

        $manager->flush();
    }

    /**
     * Indique à Doctrine qu'il faut charger CategoryFixtures avant ce fichier.
     */
    public function getDependencies(): array
    {
        return [
            CategoryFixtures::class,
        ];
    }
}
